name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: [master]

jobs:
  bof-build:
    name: Build and publish tagged release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip \
          mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib jq

      - name: Minisign
        run: |
          MINISIGN_TMP=`mktemp -d`
          cd $MINISIGN_TMP
          wget https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
          tar xvf minisign-linux-amd64.tar.gz
          mv ./minisign ~/minisign
          touch ~/minisign.key && chmod 600 ~/minisign.key
          echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key
          ls -l ~/
          realpath ~/

      - name: Check out code
        uses: actions/checkout@v2

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Packages Setup
        run: |
          mkdir packages

      - name: Kerberoast
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Kerberoast

      - name: Winver
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Winver

      - name: Psw
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Psw

      - name: Smbinfo
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Smbinfo

      - name: Askcreds
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Askcreds
      
      - name: AddMachineAccount
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh AddMachineAccount

      - name: Lapsdump
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Lapsdump

      - name: PetitPotam
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh PetitPotam

      - name: Domaininfo
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Domaininfo

      - name: KerbHash
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh KerbHash

      - name: Psc
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Psc

      - name: Psk
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Psk

      - name: Psm
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Psm

      - name: Psx
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh Psx

      - name: SprayAD
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh SprayAD

      - name: StartWebClient
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh StartWebClient

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./packages/*.tar.gz
            ./packages/*.minisig